AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ingaia-weather-api

  Sample SAM Template for ingaia-weather-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  weatherMusicApi:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: weather-music-api/
      Handler: app.lambda_handler
      Runtime: python3.7
      FunctionName: 'ingaia-weather-music-api'
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/prod'
            Method: post
